Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 225, in receive_request
    self._requestLayer.receive_request(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/requestlayer.py", line 25, in receive_request
    transaction = self._handle_get(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/requestlayer.py", line 71, in _handle_get
    transaction = self._server.resourceLayer.get_resource(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/resourcelayer.py", line 450, in get_resource
    ret = self._handle_separate_advanced(transaction, callback)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/resourcelayer.py", line 342, in _handle_separate_advanced
    return callback(request=transaction.request, response=transaction.response)
  File "/home/hongbei/Documents/coap-fuzzer/exampleresources.py", line 266, in render_GET_separate
    response.payload = self.payload
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/resources/resource.py", line 174, in payload
    raise KeyError("Content-Type not available")
KeyError: 'Content-Type not available'

Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 72, in deserialize
    num, option_length, pos = Serializer.read_option_value_len_from_byte(next_byte, pos, values)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 307, in read_option_value_len_from_byte
    length = s.unpack_from(values[pos:])[0] + 269
UnboundLocalError: local variable 's' referenced before assignment
Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 72, in deserialize
    num, option_length, pos = Serializer.read_option_value_len_from_byte(next_byte, pos, values)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 307, in read_option_value_len_from_byte
    length = s.unpack_from(values[pos:])[0] + 269
UnboundLocalError: local variable 's' referenced before assignment
Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 72, in deserialize
    num, option_length, pos = Serializer.read_option_value_len_from_byte(next_byte, pos, values)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 307, in read_option_value_len_from_byte
    length = s.unpack_from(values[pos:])[0] + 269
UnboundLocalError: local variable 's' referenced before assignment
Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 105, in deserialize
    option.value = Serializer.convert_to_raw(current_option, value, option_length)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 339, in convert_to_raw
    return bytearray(value)
OverflowError: cannot fit 'long' into an index-sized integer
Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 105, in deserialize
    option.value = Serializer.convert_to_raw(current_option, value, option_length)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 339, in convert_to_raw
    return bytearray(value)
OverflowError: cannot fit 'long' into an index-sized integer
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 225, in receive_request
    self._requestLayer.receive_request(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/requestlayer.py", line 25, in receive_request
    transaction = self._handle_get(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/requestlayer.py", line 71, in _handle_get
    transaction = self._server.resourceLayer.get_resource(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/resourcelayer.py", line 436, in get_resource
    ret = method(request=transaction.request, response=transaction.response)
  File "/home/hongbei/Documents/coap-fuzzer/exampleresources.py", line 219, in render_GET_advanced
    response.payload = self.payload
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/resources/resource.py", line 174, in payload
    raise KeyError("Content-Type not available")
KeyError: 'Content-Type not available'

Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 105, in deserialize
    option.value = Serializer.convert_to_raw(current_option, value, option_length)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 339, in convert_to_raw
    return bytearray(value)
OverflowError: cannot fit 'long' into an index-sized integer
Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 105, in deserialize
    option.value = Serializer.convert_to_raw(current_option, value, option_length)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 339, in convert_to_raw
    return bytearray(value)
OverflowError: cannot fit 'long' into an index-sized integer
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 225, in receive_request
    self._requestLayer.receive_request(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/requestlayer.py", line 25, in receive_request
    transaction = self._handle_get(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/requestlayer.py", line 71, in _handle_get
    transaction = self._server.resourceLayer.get_resource(transaction)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/resourcelayer.py", line 450, in get_resource
    ret = self._handle_separate_advanced(transaction, callback)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/layers/resourcelayer.py", line 342, in _handle_separate_advanced
    return callback(request=transaction.request, response=transaction.response)
  File "/home/hongbei/Documents/coap-fuzzer/exampleresources.py", line 266, in render_GET_separate
    response.payload = self.payload
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/resources/resource.py", line 174, in payload
    raise KeyError("Content-Type not available")
KeyError: 'Content-Type not available'

Traceback (most recent call last):
  File "coapserver.py", line 67, in <module>
    main(sys.argv[1:])
  File "coapserver.py", line 59, in main
    server.listen(10)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/server/coap.py", line 152, in listen
    message = serializer.deserialize(data, client_address)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 105, in deserialize
    option.value = Serializer.convert_to_raw(current_option, value, option_length)
  File "/home/hongbei/Documents/coap-fuzzer/coapthon/serializer.py", line 339, in convert_to_raw
    return bytearray(value)
OverflowError: cannot fit 'long' into an index-sized integer
Exception KeyboardInterrupt in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
